apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
 - ../../base


patches:
 - path: frontend_replicas.yaml
   target:
     kind: Deployment
     name: frontend

 - path: backend_replicas.yaml
   target:
     kind: Deployment
     name: api

 - path: db_replicas.yaml
   target:
     kind: Deployment
     name: database
