apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
 name: argocd-image-updater-binding
 namespace: argocd
roleRef: 
 apiGroup: rbac.authorization.k8s.io
 kind: Role
 name: argocd-image-updater-role
subjects: 
 - kind: ServiceAccount
   name: argocd-image-updater
   namespace: argocd  
