apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myClusterRoleBinding
  namespace: mynamespace
roleRef:
  kind: Role
  name: myClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: myserviceaccount
  namespace: mynamespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myClusterRole
  namespace: mynamespace
rules:
- apiGroups: [""]
  resources: ["pods","pods/log"]
  verbs: ["get","list"]

---
apiVersion: v1
kind: Secret
metadata:
  name: myserviceaccount-secret
  namespace: mynamespace
  annotations:
    kubernetes.io/service-account.name: "myserviceaccount"
type: kubernetes.io/service-account-token
