apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mynamespace
spec:
  selector: 
    app: mern-app
    role: api
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  type: ClusterIP
