apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mynamespace
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30953
    protocol: TCP
  type: NodePort
  selector:
   app: mern-app
   role: frontend
